In [1]:
import gym
from src.jss_lite.jss_lite import jss_lite


def env_creator():
    env = jss_lite(instance_path='resources/jsp_instances/standard/ft06.txt')
    return env

from wrapper.jssp_wrapper import Jssp_wrapper
import src.jss_graph_env.disjunctive_graph_jss_env as jss_env
import src.jsp_instance_parser 
from wrapper.jssp_wrapper import jssp_obs_wrapper
from wrapper.jssp_wrapper import Jssp_wrapper

def env_creator2():
    #env = discretetobox(gym.make("Taxi-v3"))
    #env = gym.make('LunarLander-v2')
    path='resources/jsp_instances/standard/ft06.txt'
    curr_instance=src.jsp_instance_parser.parse_jps_standard_specification(path)
    res,std_matrix=curr_instance
    env = jssp_obs_wrapper(jss_env.DisjunctiveGraphJssEnv(res,default_visualisations='gantt_console'))
    return env

In [2]:
env_1=env_creator()
env_2=env_creator2()

[10:16:27] INFO     parsing file 'resources/jsp_instances/standard/ft06.txt'

           INFO     instance appears to contain 6 jobs, 6 machines

In [4]:
import numpy as np
reset_1=env_1.reset()
reset_2=env_2.reset()
print(reset_1['action_mask'])
print(reset_2['action_mask'])
print(reset_1)
print(reset_2)
#print(state['obs'].shape)
#for i in range(150):
legal_action_1=env_1.get_legal_actions(reset_1)
print(legal_action_1)
action_1=np.random.choice(len(legal_action_1), 1, p=(legal_action_1 / legal_action_1.sum()))[0]

legal_action_2=reset_2['action_mask']
print(legal_action_2)
action_2=np.random.choice(len(legal_action_2), 1, p=(legal_action_2 / legal_action_2.sum()))[0]

state_1, reward_1, done_1, info_1=env_1.step(action_1)
get_state1=env_1.get_state()



[1 1 1 1 1 1 0 0 0 0 0 0]
[1 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0]
{'obs': array([1. , 0. , 0.1, 0. , 0. , 0. , 1. , 0. , 0.8, 0. , 0. , 0. , 1. ,
       0. , 0.5, 0. , 0. , 0. , 1. , 0. , 0.5, 0. , 0. , 0. , 1. , 0. ,
       0.9, 0. , 0. , 0. , 1. , 0. , 0.3, 0. , 0. , 0. , 0. , 0. , 0. ,
       0. , 0. , 0. , 1. , 0. , 0. , 0. , 0. , 0. , 1. , 0. , 0. , 0. ,
       0. , 0. , 1. , 0. , 0. , 0. , 0. , 0. , 1. , 0. , 0. , 0. , 0. ,
       0. , 1. , 0. , 0. , 0. , 0. , 0. ], dtype=float32), 'action_mask': array([1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0], dtype=int32)}
{'obs': array([0. , 0.1, 0. , ..., 0. , 0. , 0.1], dtype=float32), 'action_mask': array([1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0], dtype=int32)}
[1 1 1 1 1 1 0 0 0 0 0 0]
[1 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0]


In [7]:
print(env_1.observation)
print("")
print(get_state1.observation)

print(env_1.get_legal_actions("t"))
print("")
print(get_state1.get_legal_actions("t"))

[[1.  0.  0.1 0.  0.  0. ]
 [0.  0.  0.8 0.  0.  0.5]
 [1.  0.  0.5 0.  0.  0. ]
 [0.  0.5 0.5 0.  0.  0. ]
 [1.  0.  0.9 0.  0.  0. ]
 [0.  0.  0.3 0.  0.  0. ]
 [0.  0.  0.  0.  0.  0. ]
 [0.  0.  0.  0.  0.  0. ]
 [0.  0.  0.  0.  0.  0. ]
 [0.  0.  0.  0.  0.  0. ]
 [0.  0.  0.  0.  0.  0. ]
 [0.  0.  0.  0.  0.  0. ]]

[[1.  0.  0.1 0.  0.  0. ]
 [0.  0.  0.8 0.  0.  0.5]
 [1.  0.  0.5 0.  0.  0. ]
 [0.  0.5 0.5 0.  0.  0. ]
 [1.  0.  0.9 0.  0.  0. ]
 [0.  0.  0.3 0.  0.  0. ]
 [0.  0.  0.  0.  0.  0. ]
 [0.  0.  0.  0.  0.  0. ]
 [0.  0.  0.  0.  0.  0. ]
 [0.  0.  0.  0.  0.  0. ]
 [0.  0.  0.  0.  0.  0. ]
 [0.  0.  0.  0.  0.  0. ]]
[[nan  0.  0.]
 [ 3.  5.  0.]
 [nan  0.  0.]
 [nan  0.  0.]
 [nan  0.  0.]
 [nan  0.  0.]]

[[nan  0.  0.]
 [ 3.  5.  0.]
 [nan  0.  0.]
 [nan  0.  0.]
 [nan  0.  0.]
 [nan  0.  0.]]
